<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	<PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Notification.Infrastructure\Notification.Infrastructure.csproj" />
	<ProjectReference Include="..\Notification.Application\Notification.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
