
services:
  ecommercedb:
    image: postgres

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:3-management

  distributedcache:
    image: redis

  keycloak:
    image: quay.io/keycloak/keycloak:26.7

volumes:
  postgres_ecommercedb:
