

services:
  ecommercedb:
    container_name: ecommercedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ECommerceDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_ecommercedb:/var/lib/postgresql

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=True
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"

  messagebus:
    container_name: messagebus
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
