
services:
  ecommercedb:
    image: postgres

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:3-management

  distributedcache:
    image: redis

volumes:
  postgres_ecommercedb:
